Upload Bandit output then fail

diff --git a/.github/workflows/full.yaml b/.github/workflows/full.yaml
--- a/.github/workflows/full.yaml
+++ b/.github/workflows/full.yaml
@@ -42,12 +42,18 @@ jobs:
       run: pylint **/*.py || true  # Allow non-zero exit to not fail the workflow
 
     - name: Run Bandit security scanner
-      run: bandit -r . -f sarif -o bandit-report.sarif
+      run: bandit -r . -f sarif -o bandit-report.sarif || echo "BANDIT_FAIL=true" >> "$GITHUB_ENV"
     
     - name: Upload Bandit scan results to Github Code Scanning
       uses: github/codeql-action/upload-sarif@v2
       with:
         sarif_file: bandit-report.sarif
+    
+    - name: Exit if Bandit fails
+      run: |
+        if [ -n "$BANDIT_FAIL" ]; then
+          exit 1
+        fi
 
     - name: Run Tests
       run: nosetests tests.py
